// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC0O_yrEaeeJgNnVDdai5apmKpm6LLVLA',
    appId: '1:479321217000:web:c9974aee74951a85abf65d',
    messagingSenderId: '479321217000',
    projectId: 'flutter-push-app-b09dd',
    authDomain: 'flutter-push-app-b09dd.firebaseapp.com',
    storageBucket: 'flutter-push-app-b09dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Xl909Xf06l1rLIB04xiy5aniUHf3ISk',
    appId: '1:479321217000:android:bf25eafc2d0519cfabf65d',
    messagingSenderId: '479321217000',
    projectId: 'flutter-push-app-b09dd',
    storageBucket: 'flutter-push-app-b09dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkruuRjM6701xia0g_4A4sxjbhAT1UR60',
    appId: '1:479321217000:ios:f73823147912e324abf65d',
    messagingSenderId: '479321217000',
    projectId: 'flutter-push-app-b09dd',
    storageBucket: 'flutter-push-app-b09dd.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkruuRjM6701xia0g_4A4sxjbhAT1UR60',
    appId: '1:479321217000:ios:f73823147912e324abf65d',
    messagingSenderId: '479321217000',
    projectId: 'flutter-push-app-b09dd',
    storageBucket: 'flutter-push-app-b09dd.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC0O_yrEaeeJgNnVDdai5apmKpm6LLVLA',
    appId: '1:479321217000:web:c36b8f8dd164bcd1abf65d',
    messagingSenderId: '479321217000',
    projectId: 'flutter-push-app-b09dd',
    authDomain: 'flutter-push-app-b09dd.firebaseapp.com',
    storageBucket: 'flutter-push-app-b09dd.appspot.com',
  );
}
